version: '3'

services:

  php:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    restart: always
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lesecho
      MYSQL_USER: lesecho
      MYSQL_PASSWORD: lesecho
    ports:
      - "3306:3306"